export const works = [
  {
    _id: 1,
    title: "Netflix",
    sub_title: "Movies App",
    desc: "In this app you can sign up or sign in through firebase and make a payment and of course it is not a real payment and it is safe and then you can watch your favorite serials, multfilms, movies with interest.",
    img: "https://wallpaperaccess.com/full/2772922.png",
    source: "https://nextflixclone-app.vercel.app/",
    code: "https://github.com/liildev/netflix",
    tags: ["Next", "Redux", "Tailwind CSS", "Firebase", "TMDB API", "Stripe"],
  },
  {
    _id: 2,
    title: "Lyriks",
    sub_title: "Music Player",
    desc: "One of my favorite apps, in this app you can listen to the latest hit songs and of course for free.",
    img: "https://www.apple.com/v/apple-music/u/images/shared/og__ckjrh2mu8b2a_image.png",
    source: "https://lyriks-music.firebaseapp.com/",
    code: "https://github.com/liildev/lyriks",
    tags: [
      "Vite",
      "Redux ToolKit",
      "Tailwind CSS",
      "Firebase",
      "Shazam Core API",
    ],
  },
  {
    _id: 3,
    title: "Admins",
    sub_title: "Admin Dashboard",
    desc: "In this dashboard you can manage teams and get information desc their balance, contacts, and you can also work with calendars, forms and convenient charts, graphs.",
    img: "https://i.pinimg.com/originals/29/5a/d5/295ad5526a6c566a415776b9dede64f9.jpg",
    source: "https://adminis-app.vercel.app/",
    code: "https://github.com/liildev/admin-dashboard",
    tags: ["React", "Material UI"],
  },
  {
    _id: 4,
    title: "Countries",
    sub_title: "Information about countries",
    desc: "In this app, you can search for countries by name or by continent, and get information about their flag, population, border neighbors, and more.",
    img: "https://repository-images.githubusercontent.com/393506201/fb2ead61-3333-4b3d-9ff3-b2609cea784d",
    source: "https://countriesapi-app.vercel.app/",
    code: "https://github.com/liildev/countries-api",
    tags: ["React", "Tailwind CSS", "Restcountries API"],
  },
  {
    _id: 5,
    title: "Metaverse",
    sub_title: "Motional App",
    desc: "This is Metaverse's landing page, it's not functional because it's more designed and very motional app.",
    img: "https://business.ladn.eu/wp-content/uploads/2022/03/lancement-metaverse-college-ridouan-abagri2-1920x714.jpg?v=202212",
    source: "https://metaverses-app.vercel.app/",
    code: "https://github.com/liildev/metaverse-app/",
    tags: ["Next", "Tailwind CSS", "Framer-motion"],
  },
  {
    _id: 6,
    title: "YouTube",
    sub_title: "YouTube Lux Copy",
    desc: "I like this app very much because i can call it a lux copy of YouTube. You can login with your google account through Firebase and it is safe. In this app you can watch and search videos just like on YouTube.",
    img: "https://images5.alphacoders.com/795/795970.jpg",
    source: "https://you-tube-clone-366ff.firebaseapp.com",
    code: "https://github.com/liildev/you-tube-redux",
    tags: ["React", "Redux", "Sass", "YouTube Data API", "Firebase"],
  },
  {
    _id: 7,
    title: "HooBank",
    sub_title: "HooBank Landing Page",
    desc: "This is Hoobank's landing page, it's not functional because it's more designed with Tailwind CSS.",
    img: "https://cdn.dribbble.com/users/7202957/screenshots/16549360/desktop_-_1_4x.png",
    source: "https://project-hoobank-app.netlify.app/",
    code: "https://github.com/liildev/hoobank",
    tags: ["Vite", "Tailwind CSS"],
  },
];
