export const logos = [
  {
    path: 'html',
    title: 'HTML',
    top: '90%',
    left: '28%',
    size: 80,
    xRange: 18,
    yRange: 18,
    duration: 18,
  },
  {
    path: 'shadcn',
    title: 'ShadCN',
    top: '15%',
    left: '25%',
    size: 70,
    xRange: 20,
    yRange: 20,
    duration: 22,
  },
  {
    path: 'js',
    title: 'JavaScript',
    top: '18%',
    left: '60%',
    size: 75,
    xRange: 18,
    yRange: 18,
    duration: 20,
  },
  {
    path: 'ts',
    title: 'TypeScript',
    top: '25%',
    left: '90%',
    size: 65,
    xRange: 25,
    yRange: 25,
    duration: 24,
  },
  {
    path: 'vite',
    title: 'Vite',
    top: '70%',
    left: '10%',
    size: 75,
    xRange: 20,
    yRange: 20,
    duration: 19,
  },
  {
    path: 'next',
    title: 'Next.js',
    top: '75%',
    left: '85%',
    size: 70,
    xRange: 22,
    yRange: 22,
    duration: 21,
  },
  {
    path: 'zustand',
    title: 'Zustand',
    top: '50%',
    left: '90%',
    size: 75,
    xRange: 15,
    yRange: 15,
    duration: 23,
  },
  {
    path: 'redux',
    title: 'Redux',
    top: '85%',
    left: '50%',
    size: 80,
    xRange: 18,
    yRange: 18,
    duration: 20,
  },
  {
    path: 'tanstack',
    title: 'TanStack',
    top: '45%',
    left: '20%',
    size: 65,
    xRange: 25,
    yRange: 25,
    duration: 22,
  },
  {
    path: 'sass',
    title: 'SASS',
    top: '60%',
    left: '70%',
    size: 70,
    xRange: 20,
    yRange: 20,
    duration: 19,
  },
  {
    path: 'tailwind',
    title: 'Tailwind UI',
    top: '35%',
    left: '10%',
    size: 68,
    xRange: 16,
    yRange: 16,
    duration: 21,
  }, // an extra one
];
